---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 11198.
--- DateTime: 2022/11/26 22:11
---
if(redis.call('get',KEYS[1]) == ARGV[1]) then
    --- 释放锁
    return redis.call('del',KEYS[1])
end
return 0